no message

diff --git a/.github/workflows/reusable-workflow.yaml b/.github/workflows/reusable-workflow.yaml
--- a/.github/workflows/reusable-workflow.yaml
+++ b/.github/workflows/reusable-workflow.yaml
@@ -23,32 +23,34 @@ jobs:
           npm install shelljs@0.8.5
           ./install.sh
           echo ${{ secrets.TEST_CREDENTIALS }} > ./shared/test/test_credentials.json
-      - uses: mxcl/xcodebuild@v3
-        with:
-          xcode: ${{ inputs.xcode }}
-          platform: iOS
-          platform-version: ${{ inputs.ios }}
-          workspace: SalesforceMobileSDK.xcworkspace
-          scheme: ${{ inputs.lib }}
-          code-coverage: ${{ github.event_name == 'pull_request' }}
-          upload-logs: always
+      # - uses: mxcl/xcodebuild@v3
+      #   with:
+      #     xcode: ${{ inputs.xcode }}
+      #     platform: iOS
+      #     platform-version: ${{ inputs.ios }}
+      #     workspace: SalesforceMobileSDK.xcworkspace
+      #     scheme: ${{ inputs.lib }}
+      #     code-coverage: ${{ github.event_name == 'pull_request' }}
+      #     upload-logs: always
       - name: Static Analysis and Danger
         if: ${{ github.event_name == 'pull_request' }} && success() || failure()
-        # env:
-        #   DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        env:
+          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           xcodebuild analyze -workspace SalesforceMobileSDK.xcworkspace -scheme ${{ inputs.lib }} -sdk 'iphonesimulator' \
             CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR=./clangReport RUN_CLANG_STATIC_ANALYZER=YES | xcbeautify
-          # cd .github
-          # bundle update && bundle install
-          # bundle exec danger --dangerfile=Dangerfile.rb --danger_id="${{ inputs.lib }}" --verbose
-      - uses: MeilCli/danger-action@v6
-        if: ${{ github.event_name == 'pull_request' }} && success() || failure()
-        with:
-          plugins_file: '.github/Gemfile'
-          danger_file: '.github/Dangerfile.rb'
-          danger_id: "${{ inputs.lib }}"
-        env:
-          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          cd .github
+          bundle update && bundle install
+          bundle exec danger --dangerfile=Dangerfile.rb --danger_id="${{ inputs.lib }}" --verbose
+
+          
+      # - uses: MeilCli/danger-action@v6
+      #   if: ${{ github.event_name == 'pull_request' }} && success() || failure()
+      #   with:
+      #     plugins_file: '.github/Gemfile'
+      #     danger_file: '.github/Dangerfile.rb'
+      #     danger_id: "${{ inputs.lib }}"
+      #   env:
+      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
       
